import render_icon from "../../../templates/cofounder/components/icon.hbs";

export const COFOUNDER_ICON_NAMES = [
    "close",
    "plus",
    "minus",
    "check",
    "square",
    "square-check",
    "chevron-down",
    "chevron-right",
    "chevron-left",
    "search",
    "panel-left",
    "settings",
    "more-horizontal",
    "warning",
    "play",
    "shield",
    "copy",
    "loader-circle",
    "inbox",
    "clock",
    "activity",
    "sort-ascending",
    "circle-off",
    "at-sign",
    "smile",
    "star",
    "sun",
    "moon",
    "monitor",
    "sliders",
    "book",
    "type",
    "line-height",
    "file",
    "calendar",
    "alarm",
    "hash",
    "lock",
    "globe",
    "archive",
    "eye",
    "users",
    "user",
    "user-plus",
    "bot",
    "messages",
    "edit",
    "pencil",
    "link-alt",
    "external-link",
    "more-vertical",
    "grip-vertical",
    "trash",
    "follow",
    "unmute",
    "mute",
    "inherit",
    "placeholder",
    "reset",
    "user-group-plus",
    "user-group-x",
    "folder-cog",
    "folder-chevron",
    "folder-search",
    "preview",
    "send",
    "paperclip",
    "video",
    "phone",
    "image",
    "file-text",
    "id-card",
    "bold",
    "italic",
    "strikethrough",
    "list-ordered",
    "list",
    "quote",
    "eye-off",
    "code",
    "sigma",
    "poll",
    "list-check",
    "circle-help",
    "maximize",
    "expand",
    "minimize",
    "home",
    "mail",
    "pin",
    "pin-off",
    "palette",
    "sparkles",
    "move",
    "refresh",
    "circle-x",
    "masked-unread",
    "keyboard",
    "info",
    "life-buoy",
    "handshake",
    "building",
    "bar-chart",
    "git-pull-request",
    "credit-card",
    "heart",
    "rocket",
    "log-in",
    "log-out",
    "thumbs-up",
    "leaf",
    "utensils",
    "ball",
    "car",
    "lightbulb",
    "flag",
] as const;

export type CofounderIconName = (typeof COFOUNDER_ICON_NAMES)[number];

const COFOUNDER_ICON_NAME_SET: ReadonlySet<string> = new Set(COFOUNDER_ICON_NAMES);

export function is_icon_name(name: string): name is CofounderIconName {
    return COFOUNDER_ICON_NAME_SET.has(name);
}

export function replace_icon($root: JQuery, name: CofounderIconName): void {
    // The typed icon name renders a trusted, precompiled application template.
    // eslint-disable-next-line no-jquery/no-append-html
    $root.find(".cf-icon").replaceWith(render_icon({compact: true, name}));
}
