# Generated by Django 5.0.7 on 2026-08-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("zerver", "0806_stream_default_push_notifications")]

    operations = [
        migrations.CreateModel(
            name="GeneratedItem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "output_type",
                    models.TextField(
                        choices=[
                            ("feed_update", "Feed update"),
                            ("digest", "Digest"),
                            ("suggested_action", "Suggested action"),
                            ("progress_update", "Progress update"),
                            ("decision", "Decision"),
                            ("analysis", "Analysis"),
                        ]
                    ),
                ),
                ("module_key", models.TextField()),
                ("module_name", models.TextField()),
                ("module_version", models.TextField()),
                ("source_summary", models.TextField()),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hover_generated_item",
                        to="zerver.message",
                    ),
                ),
                ("realm", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="zerver.realm")),
            ],
        ),
        migrations.CreateModel(
            name="EvidenceLink",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.PositiveIntegerField()),
                ("provider_key", models.TextField()),
                ("provider_name", models.TextField()),
                ("display_name", models.TextField()),
                ("url", models.URLField(blank=True)),
                (
                    "generated_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_links",
                        to="hover.generateditem",
                    ),
                ),
                ("realm", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="zerver.realm")),
            ],
            options={"ordering": ["position"]},
        ),
        migrations.AddConstraint(
            model_name="evidencelink",
            constraint=models.UniqueConstraint(
                fields=("generated_item", "position"), name="hover_evidence_link_unique_position"
            ),
        ),
    ]
