# Generated by Django 5.2 on 2026-08-11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("hover", "0005_publication_sync")]

    operations = [
        migrations.CreateModel(
            name="SpaceMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.TextField(
                        choices=[("contributor", "Contributor"), ("subscriber", "Subscriber")]
                    ),
                ),
                ("date_created", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hover_space_memberships_added",
                        to="zerver.userprofile",
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="hover.space",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hover_space_memberships",
                        to="zerver.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpaceMembershipSuggestion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "suggested_role",
                    models.TextField(
                        choices=[("contributor", "Contributor"), ("subscriber", "Subscriber")]
                    ),
                ),
                (
                    "state",
                    models.TextField(
                        choices=[
                            ("pending", "Pending review"),
                            ("confirmed", "Confirmed"),
                            ("removed", "Removed"),
                        ],
                        default="pending",
                    ),
                ),
                (
                    "match_basis",
                    models.TextField(
                        choices=[
                            ("verified_email", "Verified email"),
                            ("verified_phone", "Verified phone"),
                        ]
                    ),
                ),
                (
                    "observation_basis",
                    models.CharField(
                        max_length=36,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Observation bases must be opaque observation IDs.",
                                regex="^obs_[0-9a-f]{32}$",
                            )
                        ],
                    ),
                ),
                ("date_created", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_suggestions",
                        to="hover.space",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hover_space_membership_suggestions_updated",
                        to="zerver.userprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hover_space_membership_suggestions",
                        to="zerver.userprofile",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="spacemembership",
            constraint=models.UniqueConstraint(
                fields=("space", "user"), name="hover_space_membership_unique_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="spacemembershipsuggestion",
            constraint=models.UniqueConstraint(
                fields=("space", "user"), name="hover_space_suggestion_unique_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="spacemembershipsuggestion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("match_basis__in", ["verified_email", "verified_phone"]),
                    ("observation_basis__startswith", "obs_"),
                ),
                name="hover_space_suggestion_observation_basis",
            ),
        ),
    ]
