# Generated by Django 5.2 on 2026-08-11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps
from django.db.models import Count, Q


def reconcile_duplicate_idempotency_keys(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    GeneratedItem = apps.get_model("hover", "GeneratedItem")
    duplicates = (
        GeneratedItem.objects.exclude(attachment_id=None)
        .exclude(idempotency_key=None)
        .values("attachment_id", "idempotency_key")
        .annotate(item_count=Count("id"))
        .filter(item_count__gt=1)
    )
    for duplicate in duplicates.iterator():
        duplicate_ids = list(
            GeneratedItem.objects.filter(
                attachment_id=duplicate["attachment_id"],
                idempotency_key=duplicate["idempotency_key"],
            )
            .order_by("id")
            .values_list("id", flat=True)
        )
        GeneratedItem.objects.filter(id__in=duplicate_ids[1:]).update(idempotency_key=None)


class Migration(migrations.Migration):
    dependencies = [("hover", "0006_space_membership")]

    operations = [
        migrations.AlterField(
            model_name="generateditem",
            name="publication_id",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="generateditem",
            name="publication_envelope_hash",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.RunPython(reconcile_duplicate_idempotency_keys, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="generateditem",
            constraint=models.UniqueConstraint(
                fields=("attachment", "publication_id"),
                condition=Q(attachment__isnull=False, publication_id__isnull=False),
                name="hover_generated_item_unique_attachment_publication",
            ),
        ),
        migrations.AddConstraint(
            model_name="generateditem",
            constraint=models.UniqueConstraint(
                fields=("attachment", "idempotency_key"),
                condition=Q(attachment__isnull=False, idempotency_key__isnull=False),
                name="hover_generated_item_unique_attachment_idempotency",
            ),
        ),
        migrations.AddField(
            model_name="spaceattachment",
            name="publication_sync_state",
            field=models.TextField(
                choices=[
                    ("idle", "Idle"),
                    ("leased", "Leased"),
                    ("backoff", "Retry backoff"),
                    ("blocked", "Blocked"),
                ],
                default="idle",
            ),
        ),
        migrations.AddField(
            model_name="spaceattachment",
            name="publication_sync_lease_token",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="spaceattachment",
            name="publication_sync_lease_expires_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="spaceattachment",
            name="next_publication_sync_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.CreateModel(
            name="PublicationSyncAttempt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outcome",
                    models.TextField(choices=[("success", "Success"), ("error", "Error")]),
                ),
                ("error_code", models.CharField(default="", max_length=64)),
                ("retryable", models.BooleanField(default=False)),
                ("publication_count", models.PositiveIntegerField(default=0)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("replayed_count", models.PositiveIntegerField(default=0)),
                ("requested_cursor_hash", models.CharField(default="", max_length=64)),
                ("returned_cursor_hash", models.CharField(default="", max_length=64)),
                ("date_created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "attachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publication_sync_attempts",
                        to="hover.spaceattachment",
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zerver.realm",
                    ),
                ),
            ],
        ),
    ]
