# Generated by Django 5.2 on 2026-08-11

from typing import Any

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def copy_provider_names(apps: Any, schema_editor: Any) -> None:
    Source = apps.get_model("hover", "Source")
    for source in Source.objects.select_related("account").iterator():
        source.provider_name = source.account.provider_name
        source.save(update_fields=["provider_name"])


class Migration(migrations.Migration):
    dependencies = [("hover", "0008_source_record_browsing")]

    operations = [
        migrations.AddField(
            model_name="connectedaccount",
            name="connection_kind",
            field=models.TextField(
                choices=[
                    ("remote_studio", "Remote Studio"),
                    ("native_integration", "Native integration"),
                ],
                default="remote_studio",
            ),
        ),
        migrations.AddField(
            model_name="connectedaccount",
            name="incoming_webhook_bot",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="hover_connected_account",
                to="zerver.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="external_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="source",
            name="provider_name",
            field=models.CharField(default="", max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="source",
            name="supports_live_capture",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(copy_provider_names, migrations.RunPython.noop),
        migrations.CreateModel(
            name="IntegrationRouteAssociation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "state",
                    models.TextField(
                        choices=[("active", "Active"), ("detached", "Detached")],
                        default="active",
                    ),
                ),
                ("live_since", models.DateTimeField(default=django.utils.timezone.now)),
                ("detached_at", models.DateTimeField(null=True)),
                ("date_created", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "attachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="integration_routes",
                        to="hover.spaceattachment",
                    ),
                ),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="hover_integration_routes",
                        to="zerver.userprofile",
                    ),
                ),
                (
                    "configured_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configured_hover_integration_routes",
                        to="zerver.userprofile",
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="hover_integration_routes",
                        to="zerver.stream",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntegrationMessageProvenance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("captured_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("provider_key", models.CharField(max_length=32)),
                ("provider_name", models.CharField(max_length=60)),
                ("source_type", models.CharField(max_length=64)),
                ("display_name", models.CharField(max_length=100)),
                ("external_url", models.URLField(blank=True)),
                (
                    "association",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="message_provenance",
                        to="hover.integrationrouteassociation",
                    ),
                ),
                (
                    "attachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="message_provenance",
                        to="hover.spaceattachment",
                    ),
                ),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hover_source_provenance",
                        to="zerver.message",
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="message_provenance",
                        to="hover.source",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="integrationrouteassociation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "active")),
                fields=("attachment",),
                name="hover_route_unique_active_attachment",
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationrouteassociation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "active")),
                fields=("bot",),
                name="hover_route_unique_active_bot",
            ),
        ),
    ]
