# Generated by Django 5.2.16 on 2026-08-10 21:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def seed_existing_source_capabilities(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    Source = apps.get_model("hover", "Source")
    SourceCapability = apps.get_model("hover", "SourceCapability")
    SourceCapability.objects.bulk_create(
        [
            SourceCapability(source_id=source_id, capability="message_history")
            for source_id in Source.objects.values_list("id", flat=True)
        ]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("hover", "0009_integration_provenance"),
        ("zerver", "0809_alter_realm_can_create_spaces_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleSourceRequirement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Module keys must start with a letter and contain only lowercase letters, digits, and underscores.",
                                regex="^[a-z][a-z0-9_]{0,63}$",
                            )
                        ],
                    ),
                ),
                (
                    "capability",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Module keys must start with a letter and contain only lowercase letters, digits, and underscores.",
                                regex="^[a-z][a-z0-9_]{0,63}$",
                            )
                        ],
                    ),
                ),
                ("minimum_count", models.PositiveSmallIntegerField(default=1)),
                ("maximum_count", models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="ModuleSupportedTrigger",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.TextField(
                        choices=[
                            ("manual", "Manual"),
                            ("new_source", "New Source"),
                            ("schedule", "Schedule"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="spaceattachment",
            name="state",
            field=models.TextField(
                choices=[
                    ("pending_sync", "Pending sync"),
                    ("active", "Active"),
                    ("detached", "Detached with retained history"),
                ],
                default="pending_sync",
            ),
        ),
        migrations.CreateModel(
            name="ModuleDefinition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "stable_key",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Module keys must start with a letter and contain only lowercase letters, digits, and underscores.",
                                regex="^[a-z][a-z0-9_]{0,63}$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(default="", max_length=1024)),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hover_module_definitions",
                        to="zerver.realm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModuleInstallation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "state",
                    models.TextField(
                        choices=[
                            ("configured", "Configured"),
                            ("enabled", "Enabled"),
                            ("disabled", "Disabled"),
                            ("paused_detached", "Paused after Source detach"),
                        ]
                    ),
                ),
                ("activation_timezone", models.CharField(max_length=64)),
                ("activated_at", models.DateTimeField(null=True)),
                ("processing_start_at", models.DateTimeField(null=True)),
                ("backfill_confirmed", models.BooleanField(default=False)),
                ("policy_revision", models.PositiveIntegerField(default=1)),
                ("policy_hash", models.CharField(max_length=64)),
                ("date_created", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "configured_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configured_hover_modules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "disabled_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disabled_hover_modules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "predecessor",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="successor",
                        to="hover.moduleinstallation",
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hover_module_installations",
                        to="zerver.realm",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_installations",
                        to="hover.space",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModuleInstallationBinding",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "attachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="module_bindings",
                        to="hover.spaceattachment",
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bindings",
                        to="hover.moduleinstallation",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="hover.modulesourcerequirement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModuleInstallationTrigger",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "cadence",
                    models.TextField(choices=[("daily", "Daily"), ("weekly", "Weekly")], null=True),
                ),
                ("local_time", models.TimeField(null=True)),
                ("timezone", models.CharField(default="", max_length=64)),
                ("debounce_seconds", models.PositiveIntegerField(null=True)),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggers",
                        to="hover.moduleinstallation",
                    ),
                ),
                (
                    "supported_trigger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="hover.modulesupportedtrigger",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModuleVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.CharField(max_length=32)),
                ("output_type", models.CharField(max_length=32)),
                ("runtime_key", models.CharField(max_length=100)),
                ("prompt_key", models.CharField(max_length=100)),
                ("destination_topic", models.CharField(max_length=60)),
                ("navigation_icon", models.CharField(default="zulip-icon-sparkles", max_length=64)),
                ("navigation_order", models.PositiveSmallIntegerField()),
                ("content_hash", models.CharField(max_length=64)),
                ("published_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="versions",
                        to="hover.moduledefinition",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_hover_module_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="modulesupportedtrigger",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="supported_triggers",
                to="hover.moduleversion",
            ),
        ),
        migrations.AddField(
            model_name="modulesourcerequirement",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="requirements",
                to="hover.moduleversion",
            ),
        ),
        migrations.AddField(
            model_name="moduleinstallation",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="installations",
                to="hover.moduleversion",
            ),
        ),
        migrations.CreateModel(
            name="SourceCapability",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "capability",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Module keys must start with a letter and contain only lowercase letters, digits, and underscores.",
                                regex="^[a-z][a-z0-9_]{0,63}$",
                            )
                        ],
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capabilities",
                        to="hover.source",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="moduledefinition",
            constraint=models.UniqueConstraint(
                fields=("realm", "stable_key"), name="hover_module_definition_unique_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="moduleinstallationbinding",
            constraint=models.UniqueConstraint(
                fields=("installation", "requirement", "attachment"),
                name="hover_module_binding_unique_attachment",
            ),
        ),
        migrations.AddConstraint(
            model_name="moduleinstallationtrigger",
            constraint=models.UniqueConstraint(
                fields=("installation", "supported_trigger"),
                name="hover_module_installation_trigger_unique_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="moduleversion",
            constraint=models.UniqueConstraint(
                fields=("definition", "version"), name="hover_module_version_unique_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="moduleversion",
            constraint=models.UniqueConstraint(
                fields=("definition", "content_hash"), name="hover_module_version_unique_hash"
            ),
        ),
        migrations.AddConstraint(
            model_name="modulesupportedtrigger",
            constraint=models.UniqueConstraint(
                fields=("version", "kind"), name="hover_module_supported_trigger_unique_kind"
            ),
        ),
        migrations.AddConstraint(
            model_name="modulesourcerequirement",
            constraint=models.UniqueConstraint(
                fields=("version", "key"), name="hover_module_requirement_unique_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="modulesourcerequirement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("minimum_count__gte", 1), ("maximum_count__gte", models.F("minimum_count"))
                ),
                name="hover_module_requirement_valid_cardinality",
            ),
        ),
        migrations.AddConstraint(
            model_name="moduleinstallation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("activated_at__isnull", True), ("state", "configured")),
                    ("state", "disabled"),
                    models.Q(
                        ("activated_at__isnull", False),
                        ("state__in", ["enabled", "paused_detached"]),
                    ),
                    _connector="OR",
                ),
                name="hover_module_installation_activation_matches_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="moduleinstallation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state__in", ["configured", "enabled", "paused_detached"])),
                fields=("space", "version"),
                name="hover_module_installation_unique_current_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcecapability",
            constraint=models.UniqueConstraint(
                fields=("source", "capability"), name="hover_source_capability_unique"
            ),
        ),
        migrations.RunPython(seed_existing_source_capabilities, migrations.RunPython.noop),
    ]
