# Generated by Django 5.2.16 on 2026-08-11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def initialize_reviewed_payload(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    GeneratedItem = apps.get_model("hover", "GeneratedItem")
    for item in GeneratedItem.objects.only("id", "payload").iterator():
        GeneratedItem.objects.filter(id=item.id).update(reviewed_payload=item.payload)


class Migration(migrations.Migration):
    dependencies = [
        ("hover", "0010_module_installations"),
        ("zerver", "0809_alter_realm_can_create_spaces_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="generateditem",
            name="reviewed_payload",
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(initialize_reviewed_payload, migrations.RunPython.noop),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "response_type",
                    models.TextField(choices=[("reply", "Reply"), ("review", "Review")]),
                ),
                ("clarification_required", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "generated_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="hover.generateditem",
                    ),
                ),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hover_response",
                        to="zerver.message",
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zerver.realm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Revision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_path", models.TextField()),
                ("previous_value", models.JSONField(null=True)),
                ("new_value", models.JSONField(null=True)),
                ("reason", models.TextField(default="")),
                ("date_created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="hover_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "generated_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="hover.generateditem",
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zerver.realm",
                    ),
                ),
                (
                    "response",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="revision",
                        to="hover.response",
                    ),
                ),
            ],
            options={"ordering": ["date_created", "id"]},
        ),
    ]
