# Generated by Django 5.2 on 2026-08-11

import re
from datetime import date

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

PERSON_REF = re.compile(r"^person_[0-9a-f]{32}$")


def _proposal(payload: object) -> tuple[str, str, str, date | None] | None:
    if not isinstance(payload, dict) or set(payload) != {
        "contract",
        "schema_version",
        "wording",
        "proposed_assignee",
        "proposed_due_date",
    }:
        return None
    if payload["contract"] != "suggested_action" or payload["schema_version"] != "1.0":
        return None
    wording = payload["wording"]
    if not isinstance(wording, str) or not wording.strip() or len(wording) > 50_000:
        return None
    wording = " ".join(wording.split())
    assignee_ref = ""
    assignee_name = ""
    assignee = payload["proposed_assignee"]
    if assignee is not None:
        if (
            not isinstance(assignee, dict)
            or set(assignee) != {"kind", "ref", "display_name"}
            or assignee["kind"] not in {"user", "member"}
            or not isinstance(assignee["ref"], str)
            or PERSON_REF.fullmatch(assignee["ref"]) is None
            or not isinstance(assignee["display_name"], str)
            or not assignee["display_name"]
            or len(assignee["display_name"]) > 200
        ):
            return None
        assignee_ref = assignee["ref"]
        assignee_name = assignee["display_name"]
    raw_due_date = payload["proposed_due_date"]
    due_date = None
    if raw_due_date is not None:
        if not isinstance(raw_due_date, str):
            return None
        try:
            due_date = date.fromisoformat(raw_due_date)
        except ValueError:
            return None
    return wording, assignee_ref, assignee_name, due_date


def backfill_suggested_actions(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    GeneratedItem = apps.get_model("hover", "GeneratedItem")
    SuggestedAction = apps.get_model("hover", "SuggestedAction")
    rows = (
        GeneratedItem.objects.filter(output_type="suggested_action", attachment__isnull=False)
        .select_related("attachment__space__stream", "message")
        .only(
            "id",
            "realm_id",
            "payload",
            "reviewed_payload",
            "message__recipient_id",
            "attachment__space_id",
            "attachment__space__realm_id",
            "attachment__space__state",
            "attachment__space__stream__recipient_id",
        )
    )
    for item in rows.iterator(chunk_size=500):
        if SuggestedAction.objects.filter(generated_item_id=item.id).exists():
            continue
        space = item.attachment.space
        if (
            item.realm_id != space.realm_id
            or space.state != "launched"
            or space.stream_id is None
            or item.message.recipient_id != space.stream.recipient_id
        ):
            continue
        original = _proposal(item.payload)
        current = _proposal(item.reviewed_payload or item.payload)
        if original is None or current is None:
            continue
        wording, _current_ref, _current_name, due_date = current
        _original_wording, assignee_ref, assignee_name, _original_due_date = original
        SuggestedAction.objects.create(
            realm_id=item.realm_id,
            space_id=space.id,
            generated_item_id=item.id,
            state="pending",
            wording=wording,
            proposed_assignee_ref=assignee_ref,
            proposed_assignee_display_name=assignee_name,
            due_date=due_date,
            version=1,
        )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("hover", "0012_material_review_requests"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SuggestedAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "state",
                    models.TextField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("not_action", "Not an action"),
                        ],
                        default="pending",
                    ),
                ),
                ("wording", models.TextField()),
                (
                    "proposed_assignee_ref",
                    models.CharField(
                        blank=True,
                        max_length=39,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Proposed assignees must use opaque person references.",
                                regex="^person_[0-9a-f]{32}$",
                            )
                        ],
                    ),
                ),
                ("proposed_assignee_display_name", models.CharField(blank=True, max_length=200)),
                ("due_date", models.DateField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("date_created", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="hover_assigned_suggested_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "generated_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="suggested_action",
                        to="hover.generateditem",
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hover_suggested_actions",
                        to="zerver.realm",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_actions",
                        to="hover.space",
                    ),
                ),
            ],
        ),
        AddIndexConcurrently(
            model_name="suggestedaction",
            index=models.Index(fields=["space", "state"], name="hover_action_space_state"),
        ),
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("state", models.TextField(choices=[("active", "Active")], default="active")),
                ("wording", models.TextField()),
                ("due_date", models.DateField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("date_created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="hover_todos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="hover_created_todos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hover_todos",
                        to="zerver.realm",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="todos",
                        to="hover.space",
                    ),
                ),
                (
                    "suggested_action",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="todo",
                        to="hover.suggestedaction",
                    ),
                ),
            ],
        ),
        AddIndexConcurrently(
            model_name="todo",
            index=models.Index(fields=["space", "state"], name="hover_todo_space_state"),
        ),
        migrations.CreateModel(
            name="SuggestedActionTransition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("request_id", models.UUIDField()),
                (
                    "kind",
                    models.TextField(
                        choices=[
                            ("approve", "Approve"),
                            ("not_action", "Not an action"),
                            ("restore", "Restore"),
                        ]
                    ),
                ),
                (
                    "from_state",
                    models.TextField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("not_action", "Not an action"),
                        ]
                    ),
                ),
                (
                    "to_state",
                    models.TextField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("not_action", "Not an action"),
                        ]
                    ),
                ),
                ("reason", models.TextField(default="")),
                ("before_wording", models.TextField()),
                ("after_wording", models.TextField()),
                ("before_assignee_id", models.PositiveIntegerField(null=True)),
                ("after_assignee_id", models.PositiveIntegerField(null=True)),
                ("before_due_date", models.DateField(null=True)),
                ("after_due_date", models.DateField(null=True)),
                ("date_created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="transitions",
                        to="hover.suggestedaction",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="hover_action_transitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "todo",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="approval_transition",
                        to="hover.todo",
                    ),
                ),
            ],
            options={"ordering": ["date_created", "id"]},
        ),
        migrations.AddConstraint(
            model_name="suggestedactiontransition",
            constraint=models.UniqueConstraint(
                fields=("action", "request_id"), name="hover_action_transition_unique_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="suggestedactiontransition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("from_state", "pending"), ("kind", "approve"), ("to_state", "approved")
                    ),
                    models.Q(
                        ("from_state", "pending"),
                        ("kind", "not_action"),
                        ("to_state", "not_action"),
                    ),
                    models.Q(
                        ("from_state", "not_action"), ("kind", "restore"), ("to_state", "pending")
                    ),
                    _connector="OR",
                ),
                name="hover_action_transition_legal_state",
            ),
        ),
        migrations.CreateModel(
            name="TodoEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("kind", models.TextField(choices=[("approved", "Approved")])),
                ("version", models.PositiveIntegerField(default=1)),
                ("date_created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="hover_todo_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "todo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="events",
                        to="hover.todo",
                    ),
                ),
                (
                    "transition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="todo_event",
                        to="hover.suggestedactiontransition",
                    ),
                ),
            ],
            options={"ordering": ["date_created", "id"]},
        ),
        migrations.RunPython(
            backfill_suggested_actions,
            migrations.RunPython.noop,
            atomic=True,
        ),
    ]
