# Generated by Django 5.2 on 2026-08-11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def backfill_approval_events(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    TodoEvent = apps.get_model("hover", "TodoEvent")
    for event in TodoEvent.objects.select_related("todo", "transition").iterator(chunk_size=500):
        event.request_id = event.transition.request_id
        event.previous_state = ""
        event.new_state = "active"
        event.previous_assignee_id = None
        event.new_assignee_id = event.todo.assignee_id
        event.save(
            update_fields=[
                "request_id",
                "previous_state",
                "new_state",
                "previous_assignee",
                "new_assignee",
            ]
        )


class Migration(migrations.Migration):
    dependencies = [("hover", "0013_suggested_action_workflow")]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="todo",
            name="date_updated",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="todo",
            name="state",
            field=models.TextField(
                choices=[("active", "Active"), ("completed", "Completed")], default="active"
            ),
        ),
        migrations.AddConstraint(
            model_name="todo",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("completed_at__isnull", True), ("state", "active"))
                    | models.Q(("completed_at__isnull", False), ("state", "completed"))
                ),
                name="hover_todo_completion_matches_state",
            ),
        ),
        migrations.AlterField(
            model_name="todoevent",
            name="kind",
            field=models.TextField(
                choices=[
                    ("approved", "Approved"),
                    ("assigned", "Assigned"),
                    ("reassigned", "Reassigned"),
                    ("completed", "Completed"),
                    ("reopened", "Reopened"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="todoevent",
            name="transition",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="todo_event",
                to="hover.suggestedactiontransition",
            ),
        ),
        migrations.AddField(
            model_name="todoevent",
            name="request_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="todoevent",
            name="previous_state",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="todoevent",
            name="new_state",
            field=models.TextField(
                choices=[("active", "Active"), ("completed", "Completed")], default="active"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="todoevent",
            name="previous_assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="todoevent",
            name="new_assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="todoevent",
            name="reason",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="todoevent",
            name="notification_message",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="hover_todo_notification",
                to="zerver.message",
            ),
        ),
        migrations.RunPython(backfill_approval_events, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="todoevent",
            name="request_id",
            field=models.UUIDField(),
        ),
        migrations.AddConstraint(
            model_name="todoevent",
            constraint=models.UniqueConstraint(
                fields=("todo", "request_id"), name="hover_todo_event_unique_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="todoevent",
            constraint=models.UniqueConstraint(
                fields=("todo", "version"), name="hover_todo_event_unique_version"
            ),
        ),
    ]
