# Generated by Django 5.2 on 2026-08-11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("hover", "0014_durable_todo_events")]

    operations = [
        migrations.CreateModel(
            name="PersonalEdition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "teammate_ref",
                    models.CharField(
                        max_length=39,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Participant references must be opaque participant IDs.",
                                regex="^person_[0-9a-f]{32}$",
                            )
                        ],
                    ),
                ),
                ("publication_id", models.TextField()),
                ("idempotency_key", models.TextField()),
                ("publication_envelope_hash", models.CharField(max_length=64)),
                (
                    "source_ref",
                    models.CharField(
                        max_length=36,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Source references must be opaque Studio source IDs.",
                                regex="^src_[0-9a-f]{32}$",
                            )
                        ],
                    ),
                ),
                (
                    "edition",
                    models.TextField(
                        choices=[
                            ("morning", "Morning Daily Brief"),
                            ("end_of_day", "End-of-Day Roundup"),
                        ]
                    ),
                ),
                ("payload", models.JSONField()),
                ("evidence_refs", models.JSONField(default=list)),
                ("covered_start_at", models.DateTimeField()),
                ("covered_end_at", models.DateTimeField()),
                ("producing_version", models.TextField()),
                ("generated_at", models.DateTimeField()),
                ("published_at", models.DateTimeField()),
                ("date_created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="personal_editions",
                        to="hover.connectedaccount",
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hover_personal_editions",
                        to="zerver.realm",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="hover_personal_editions",
                        to="zerver.userprofile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "edition", "-covered_end_at"],
                        name="hover_edition_user_latest",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "publication_id"),
                        name="hover_edition_unique_publication",
                    ),
                    models.UniqueConstraint(
                        fields=("account", "idempotency_key"),
                        name="hover_edition_unique_idempotency",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PersonalEditionSyncState",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "teammate_ref",
                    models.CharField(
                        max_length=39,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Participant references must be opaque participant IDs.",
                                regex="^person_[0-9a-f]{32}$",
                            )
                        ],
                    ),
                ),
                ("start_at", models.DateTimeField()),
                ("cursor", models.TextField(default="")),
                ("last_sync_at", models.DateTimeField(null=True)),
                ("last_error", models.CharField(default="", max_length=64)),
                ("sync_failures", models.PositiveIntegerField(default=0)),
                ("date_created", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_edition_sync_states",
                        to="hover.connectedaccount",
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hover_personal_edition_sync_states",
                        to="zerver.realm",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hover_personal_edition_sync_states",
                        to="zerver.userprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "user", "teammate_ref"),
                        name="hover_edition_sync_unique_stream",
                    )
                ]
            },
        ),
    ]
