# Generated by Django 5.2.16 on 2026-08-11 02:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hover", "0017_participant_selector_reconciliation"),
        ("zerver", "0809_alter_realm_can_create_spaces_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="personaleditionsyncstate",
            name="hover_edition_sync_unique_stream",
        ),
        migrations.AddField(
            model_name="spacemembership",
            name="personal_editions_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="personaleditionsyncstate",
            constraint=models.UniqueConstraint(
                fields=("account", "user", "teammate_ref"), name="hover_edition_sync_unique_target"
            ),
        ),
    ]
