# Generated by Django 5.2.16 on 2026-08-16 18:34

import hashlib
import json

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps
from typing_extensions import Any

PREBUILT_MODULES = (
    (
        "conversation_digest",
        "Conversation Digest",
        "Summarize important activity from attached conversations.",
        "digest",
        "Conversation Digest",
        "zulip-icon-align-left",
        10,
        ("manual", "new_source", "schedule"),
        10,
    ),
    (
        "progress_tracker",
        "Progress Tracker",
        "Track progress and changes across attached conversations.",
        "progress_update",
        "Progress Tracker",
        "zulip-icon-trending-up",
        20,
        ("manual", "new_source", "schedule"),
        10,
    ),
    (
        "suggested_actions",
        "Suggested Actions",
        "Identify concrete follow-up work.",
        "suggested_action",
        "Suggested Actions",
        "zulip-icon-sparkles",
        30,
        ("manual", "new_source", "schedule"),
        10,
    ),
    (
        "decisions",
        "Decisions",
        "Capture decisions and their supporting context.",
        "decision",
        "Decisions",
        "zulip-icon-check-circle",
        40,
        ("manual", "new_source", "schedule"),
        10,
    ),
    (
        "marketing_digest",
        "Marketing Digest",
        "Prepare a marketing-focused digest from one attached Source.",
        "digest",
        "Marketing Digest",
        "zulip-icon-megaphone",
        50,
        ("manual", "schedule"),
        1,
    ),
    (
        "topic_analysis",
        "Topic Analysis",
        "Analyze themes in one attached Source.",
        "analysis",
        "Topic Analysis",
        "zulip-icon-chart-bar",
        60,
        ("manual", "schedule"),
        1,
    ),
    (
        "signal_monitor",
        "Signal Monitor",
        "Monitor configured Sources for reviewed high-signal changes.",
        "analysis",
        "Signal Monitor",
        "zulip-icon-bell",
        70,
        ("manual", "new_source", "schedule"),
        10,
    ),
)


def _canonical_hash(payload: dict[str, Any]) -> str:
    return hashlib.sha256(
        json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()


def seed_and_backfill_pipeline_contracts(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    ModuleDefinition = apps.get_model("hover", "ModuleDefinition")
    ModuleSourceRequirement = apps.get_model("hover", "ModuleSourceRequirement")
    ModuleSupportedTrigger = apps.get_model("hover", "ModuleSupportedTrigger")
    ModuleVersion = apps.get_model("hover", "ModuleVersion")
    Realm = apps.get_model("zerver", "Realm")

    default_input_contract = {"kind": "attached_sources", "record_type": "message"}
    default_lookback_seconds = 30 * 24 * 60 * 60
    default_maximum_runtime_seconds = 300

    for realm in Realm.objects.filter(hover_enabled=True).iterator():
        for (
            key,
            name,
            description,
            output_type,
            destination_topic,
            navigation_icon,
            navigation_order,
            triggers,
            maximum_count,
        ) in PREBUILT_MODULES:
            definition, _ = ModuleDefinition.objects.get_or_create(
                realm=realm,
                stable_key=key,
                defaults={"name": name, "description": description},
            )
            version, _ = ModuleVersion.objects.get_or_create(
                definition=definition,
                version="1.0.0",
                defaults={
                    "output_type": output_type,
                    "runtime_key": f"hover.{key}.v1",
                    "prompt_key": f"hover.{key}.v1",
                    "input_contract": default_input_contract,
                    "lookback_seconds": default_lookback_seconds,
                    "integration_keys": [],
                    "destination_topic": destination_topic,
                    "navigation_icon": navigation_icon,
                    "navigation_order": navigation_order,
                    "output_template": {
                        "format": "hover_generated_update",
                        "title": name,
                    },
                    "maximum_runtime_seconds": default_maximum_runtime_seconds,
                    "content_hash": "0" * 64,
                },
            )
            ModuleSourceRequirement.objects.get_or_create(
                version=version,
                key="conversation_history",
                defaults={
                    "capability": "message_history",
                    "minimum_count": 1,
                    "maximum_count": maximum_count,
                },
            )
            for trigger in triggers:
                ModuleSupportedTrigger.objects.get_or_create(version=version, kind=trigger)

    versions = ModuleVersion.objects.select_related("definition").prefetch_related(
        "requirements", "supported_triggers"
    )
    for version in versions.iterator(chunk_size=100):
        input_contract = version.input_contract or default_input_contract
        lookback_seconds = version.lookback_seconds or default_lookback_seconds
        integration_keys = version.integration_keys or []
        output_template = version.output_template or {
            "format": "hover_generated_update",
            "title": version.definition.name,
        }
        maximum_runtime_seconds = version.maximum_runtime_seconds or default_maximum_runtime_seconds
        requirements = sorted(
            (
                {
                    "key": requirement.key,
                    "capability": requirement.capability,
                    "minimum_count": requirement.minimum_count,
                    "maximum_count": requirement.maximum_count,
                }
                for requirement in version.requirements.all()
            ),
            key=lambda requirement: requirement["key"],
        )
        supported_triggers = sorted(trigger.kind for trigger in version.supported_triggers.all())
        contract = {
            "definition_key": version.definition.stable_key,
            "version": version.version,
            "input_contract": input_contract,
            "lookback_seconds": lookback_seconds,
            "runtime_key": version.runtime_key,
            "prompt_key": version.prompt_key,
            "integration_keys": integration_keys,
            "output_type": version.output_type,
            "output_template": output_template,
            "maximum_runtime_seconds": maximum_runtime_seconds,
            "destination_topic": version.destination_topic,
            "navigation_icon": version.navigation_icon,
            "navigation_order": version.navigation_order,
            "requirements": requirements,
            "supported_triggers": supported_triggers,
        }
        ModuleVersion.objects.filter(id=version.id).update(
            input_contract=input_contract,
            lookback_seconds=lookback_seconds,
            integration_keys=integration_keys,
            output_template=output_template,
            maximum_runtime_seconds=maximum_runtime_seconds,
            content_hash=_canonical_hash(contract),
        )


class Migration(migrations.Migration):
    dependencies = [
        ("hover", "0018_pilot_personal_edition_enrollment"),
        ("zerver", "0809_alter_realm_can_create_spaces_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleDefinitionArchive",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("archived_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="ModuleDraft",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "stable_key",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Module keys must start with a letter and contain only lowercase letters, digits, and underscores.",
                                regex="^[a-z][a-z0-9_]{0,63}$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(default="", max_length=1024)),
                ("version", models.CharField(max_length=32)),
                (
                    "state",
                    models.TextField(
                        choices=[("draft", "Draft"), ("published", "Published")], default="draft"
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("output_type", models.CharField(max_length=32)),
                ("runtime_key", models.CharField(max_length=100)),
                ("prompt_key", models.CharField(max_length=100)),
                ("input_contract", models.JSONField(default=dict)),
                ("lookback_seconds", models.PositiveIntegerField(default=86400)),
                ("integration_keys", models.JSONField(default=list)),
                ("destination_topic", models.CharField(max_length=60)),
                ("navigation_icon", models.CharField(default="zulip-icon-sparkles", max_length=64)),
                ("navigation_order", models.PositiveSmallIntegerField(default=100)),
                ("output_template", models.JSONField(default=dict)),
                ("maximum_runtime_seconds", models.PositiveSmallIntegerField(default=300)),
                ("requirements", models.JSONField(default=list)),
                ("supported_triggers", models.JSONField(default=list)),
                ("date_created", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ModuleDraftCollaborator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="ModuleVersionArchive",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("archived_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="PipelineCreatorAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("granted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("revoked_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name="moduleversion",
            name="input_contract",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="moduleversion",
            name="integration_keys",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="moduleversion",
            name="is_sealed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="moduleversion",
            name="lookback_seconds",
            field=models.PositiveIntegerField(default=86400),
        ),
        migrations.AddField(
            model_name="moduleversion",
            name="maximum_runtime_seconds",
            field=models.PositiveSmallIntegerField(default=300),
        ),
        migrations.AddField(
            model_name="moduleversion",
            name="output_template",
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(
            seed_and_backfill_pipeline_contracts,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="moduleversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("lookback_seconds__gte", 1)),
                name="hover_module_version_positive_lookback",
            ),
        ),
        migrations.AddConstraint(
            model_name="moduleversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("maximum_runtime_seconds__gte", 1), ("maximum_runtime_seconds__lte", 3600)
                ),
                name="hover_module_version_runtime_under_cap",
            ),
        ),
        migrations.AddField(
            model_name="moduledefinitionarchive",
            name="archived_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archived_module_definitions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="moduledefinitionarchive",
            name="definition",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="archive_record",
                to="hover.moduledefinition",
            ),
        ),
        migrations.AddField(
            model_name="moduledraft",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="authored_hover_module_drafts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="moduledraft",
            name="based_on_version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="successor_drafts",
                to="hover.moduleversion",
            ),
        ),
        migrations.AddField(
            model_name="moduledraft",
            name="definition",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="drafts",
                to="hover.moduledefinition",
            ),
        ),
        migrations.AddField(
            model_name="moduledraft",
            name="published_version",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="originating_draft",
                to="hover.moduleversion",
            ),
        ),
        migrations.AddField(
            model_name="moduledraft",
            name="realm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hover_module_drafts",
                to="zerver.realm",
            ),
        ),
        migrations.AddField(
            model_name="moduledraftcollaborator",
            name="added_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="added_module_draft_collaborators",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="moduledraftcollaborator",
            name="draft",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collaborators",
                to="hover.moduledraft",
            ),
        ),
        migrations.AddField(
            model_name="moduledraftcollaborator",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collaborating_hover_module_drafts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="moduleversionarchive",
            name="archived_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archived_module_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="moduleversionarchive",
            name="version",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="archive_record",
                to="hover.moduleversion",
            ),
        ),
        migrations.AddField(
            model_name="pipelinecreatorassignment",
            name="granted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="granted_pipeline_creator_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pipelinecreatorassignment",
            name="realm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pipeline_creator_assignments",
                to="zerver.realm",
            ),
        ),
        migrations.AddField(
            model_name="pipelinecreatorassignment",
            name="revoked_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revoked_pipeline_creator_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pipelinecreatorassignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hover_pipeline_creator_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="moduledraft",
            constraint=models.UniqueConstraint(
                condition=models.Q(("based_on_version__isnull", False), ("state", "draft")),
                fields=("author", "based_on_version"),
                name="hover_module_draft_unique_author_successor",
            ),
        ),
        migrations.AddConstraint(
            model_name="moduledraft",
            constraint=models.UniqueConstraint(
                condition=models.Q(("definition__isnull", True), ("state", "draft")),
                fields=("realm", "stable_key"),
                name="hover_module_draft_unique_new_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="moduledraft",
            constraint=models.CheckConstraint(
                condition=models.Q(("lookback_seconds__gte", 1)),
                name="hover_module_draft_positive_lookback",
            ),
        ),
        migrations.AddConstraint(
            model_name="moduledraft",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("maximum_runtime_seconds__gte", 1), ("maximum_runtime_seconds__lte", 3600)
                ),
                name="hover_module_draft_runtime_under_cap",
            ),
        ),
        migrations.AddConstraint(
            model_name="moduledraft",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("published_version__isnull", True), ("state", "draft")),
                    models.Q(("published_version__isnull", False), ("state", "published")),
                    _connector="OR",
                ),
                name="hover_module_draft_publication_matches_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="moduledraftcollaborator",
            constraint=models.UniqueConstraint(
                fields=("draft", "user"), name="hover_module_draft_unique_collaborator"
            ),
        ),
        migrations.AddConstraint(
            model_name="pipelinecreatorassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("revoked_at__isnull", True)),
                fields=("realm", "user"),
                name="hover_pipeline_creator_unique_active",
            ),
        ),
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION hover_reject_sealed_module_version_mutation()
                RETURNS trigger AS $$
                BEGIN
                    IF TG_OP = 'DELETE' THEN
                        IF OLD.is_sealed THEN
                            RAISE EXCEPTION 'Published Module versions are immutable.';
                        END IF;
                        RETURN OLD;
                    END IF;
                    IF OLD.is_sealed AND NOT (
                        OLD.published_by_id IS NOT NULL
                        AND NEW.published_by_id IS NULL
                        AND (to_jsonb(NEW) - 'published_by_id') =
                            (to_jsonb(OLD) - 'published_by_id')
                    ) THEN
                        RAISE EXCEPTION 'Published Module versions are immutable.';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER hover_module_version_immutable
                BEFORE UPDATE OR DELETE ON hover_moduleversion
                FOR EACH ROW EXECUTE FUNCTION hover_reject_sealed_module_version_mutation();

                CREATE FUNCTION hover_reject_sealed_module_child_mutation()
                RETURNS trigger AS $$
                DECLARE
                    target_version_id integer;
                    target_is_sealed boolean;
                BEGIN
                    IF TG_OP = 'DELETE' THEN
                        target_version_id := OLD.version_id;
                    ELSE
                        target_version_id := NEW.version_id;
                    END IF;
                    SELECT is_sealed INTO target_is_sealed
                    FROM hover_moduleversion
                    WHERE id = target_version_id;
                    IF target_is_sealed THEN
                        RAISE EXCEPTION 'Published Module child contracts are immutable.';
                    END IF;
                    IF TG_OP = 'DELETE' THEN
                        RETURN OLD;
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER hover_module_requirement_immutable
                BEFORE INSERT OR UPDATE OR DELETE ON hover_modulesourcerequirement
                FOR EACH ROW EXECUTE FUNCTION hover_reject_sealed_module_child_mutation();

                CREATE TRIGGER hover_module_trigger_immutable
                BEFORE INSERT OR UPDATE OR DELETE ON hover_modulesupportedtrigger
                FOR EACH ROW EXECUTE FUNCTION hover_reject_sealed_module_child_mutation();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS hover_module_trigger_immutable
                    ON hover_modulesupportedtrigger;
                DROP TRIGGER IF EXISTS hover_module_requirement_immutable
                    ON hover_modulesourcerequirement;
                DROP FUNCTION IF EXISTS hover_reject_sealed_module_child_mutation();
                DROP TRIGGER IF EXISTS hover_module_version_immutable ON hover_moduleversion;
                DROP FUNCTION IF EXISTS hover_reject_sealed_module_version_mutation();
            """,
        ),
    ]
