# Generated by Django 5.2 on 2026-08-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("hover", "0019_pipeline_library")]

    operations = [
        migrations.AddField(
            model_name="connectedaccount",
            name="link_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="connectedaccount",
            name="link_state",
            field=models.TextField(
                choices=[
                    ("none", "Not linked"),
                    ("pending", "Pending"),
                    ("linked", "Linked"),
                    ("expired", "Expired"),
                    ("failed", "Failed"),
                ],
                default="none",
            ),
        ),
    ]
