# Generated by Django 5.2 on 2026-08-28

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def seed_topic_owners(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Message = apps.get_model("zerver", "Message")
    Space = apps.get_model("hover", "Space")
    SpaceAttachment = apps.get_model("hover", "SpaceAttachment")
    ModuleInstallation = apps.get_model("hover", "ModuleInstallation")
    used_topics: dict[int, set[str]] = {}
    for space in Space.objects.select_related("stream").filter(stream__isnull=False).iterator():
        used_topics[space.id] = {
            topic.casefold()
            for topic in Message.objects.filter(
                recipient_id=space.stream.recipient_id,
                is_channel_message=True,
            )
            .values_list("subject", flat=True)
            .distinct()
        }
    for attachment in SpaceAttachment.objects.select_related("source").order_by("id").iterator():
        used = used_topics.setdefault(attachment.space_id, set())
        base = attachment.source.display_name.strip()[:60] or "Source"
        candidate = base
        suffix = 2
        while candidate.casefold() in used:
            ending = f" ({suffix})"
            candidate = f"{base[: 60 - len(ending)]}{ending}"
            suffix += 1
        used.add(candidate.casefold())
        attachment.destination_topic = candidate
        attachment.save(update_fields=["destination_topic"])
    used_labels = {space_id: set(topics) for space_id, topics in used_topics.items()}
    for installation in (
        ModuleInstallation.objects.select_related("version__definition").order_by("id").iterator()
    ):
        base = installation.version.definition.name.strip()[:60] or "Summary"
        candidate = base
        if installation.state in ["configured", "enabled", "paused_detached"]:
            used = used_labels.setdefault(installation.space_id, set())
            suffix = 2
            while candidate.casefold() in used:
                ending = f" ({suffix})"
                candidate = f"{base[: 60 - len(ending)]}{ending}"
                suffix += 1
            used.add(candidate.casefold())
        installation.label = candidate
        installation.save(update_fields=["label"])


class Migration(migrations.Migration):
    dependencies = [
        ("hover", "0020_whatsapp_account_linking"),
        ("zerver", "0810_remove_realm_hover_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="spaceattachment",
            name="destination_topic",
            field=models.CharField(default="", max_length=60),
        ),
        migrations.AddField(
            model_name="moduleinstallation",
            name="label",
            field=models.CharField(default="", max_length=60),
        ),
        migrations.AddField(
            model_name="moduleinstallation",
            name="summary_stream",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="hover_summary_installation",
                to="zerver.stream",
            ),
        ),
        migrations.RunPython(seed_topic_owners, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="spaceattachment",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("destination_topic"),
                models.F("space"),
                condition=models.Q(("destination_topic", ""), _negated=True),
                name="hover_space_attachment_unique_topic",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="moduleinstallation",
            name="hover_module_installation_unique_current_version",
        ),
        migrations.AddConstraint(
            model_name="moduleinstallation",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("label"),
                models.F("space"),
                condition=models.Q(state__in=["configured", "enabled", "paused_detached"]),
                name="hover_module_installation_unique_current_label",
            ),
        ),
        migrations.CreateModel(
            name="SummaryTopicInput",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("topic_name", models.CharField(max_length=60)),
                ("kind", models.TextField(choices=[("regular", "Regular"), ("source", "Source")])),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary_inputs",
                        to="hover.moduleinstallation",
                    ),
                ),
                (
                    "source_attachment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="summary_inputs",
                        to="hover.spaceattachment",
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="hover_summary_inputs",
                        to="zerver.stream",
                    ),
                ),
            ],
            options={"ordering": ["position"]},
        ),
        migrations.AddConstraint(
            model_name="summarytopicinput",
            constraint=models.UniqueConstraint(
                fields=("installation", "position"), name="hover_summary_input_unique_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="summarytopicinput",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("topic_name"),
                models.F("installation"),
                models.F("stream"),
                name="hover_summary_input_unique_topic",
            ),
        ),
        migrations.AddConstraint(
            model_name="summarytopicinput",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "source"), ("source_attachment__isnull", False)),
                    models.Q(("kind", "regular"), ("source_attachment__isnull", True)),
                    _connector="OR",
                ),
                name="hover_summary_input_source_matches_kind",
            ),
        ),
        migrations.AddField(
            model_name="generateditem",
            name="installation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="generated_items",
                to="hover.moduleinstallation",
            ),
        ),
        migrations.AddField(
            model_name="evidencelink",
            name="citation_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="hover_evidence_citations",
                to="zerver.message",
            ),
        ),
        migrations.CreateModel(
            name="GeneratedInputSnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("topic_name", models.CharField(max_length=60)),
                ("kind", models.TextField(choices=[("regular", "Regular"), ("source", "Source")])),
                ("provider_name", models.CharField(default="", max_length=60)),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "generated_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="input_snapshots",
                        to="hover.generateditem",
                    ),
                ),
                (
                    "source_attachment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="hover.spaceattachment",
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="zerver.stream",
                    ),
                ),
            ],
            options={"ordering": ["position"]},
        ),
        migrations.AddConstraint(
            model_name="generatedinputsnapshot",
            constraint=models.UniqueConstraint(
                fields=("generated_item", "position"),
                name="hover_generated_input_unique_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="generatedinputsnapshot",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("topic_name"),
                models.F("generated_item"),
                models.F("stream"),
                name="hover_generated_input_unique_topic",
            ),
        ),
        migrations.AddConstraint(
            model_name="generatedinputsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "source"), ("source_attachment__isnull", False)),
                    models.Q(("kind", "regular"), ("source_attachment__isnull", True)),
                    _connector="OR",
                ),
                name="hover_generated_input_source_matches_kind",
            ),
        ),
        migrations.AlterField(
            model_name="generateditem",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="generated_items",
                to="hover.spaceattachment",
            ),
        ),
        migrations.AlterField(
            model_name="evidencelink",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="evidence_links",
                to="hover.source",
            ),
        ),
        migrations.AlterField(
            model_name="evidencelink",
            name="evidence_ref",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="evidencelink",
            name="provider_key",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="evidencelink",
            name="provider_name",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="evidencelink",
            name="display_name",
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name="generateditem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("attachment__isnull", False), ("installation__isnull", True)),
                    models.Q(("attachment__isnull", True), ("installation__isnull", False)),
                    _connector="OR",
                ),
                name="hover_generated_item_exactly_one_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencelink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("citation_message__isnull", False),
                        ("evidence_ref", ""),
                        ("source__isnull", True),
                    ),
                    models.Q(
                        ("citation_message__isnull", True),
                        ("source__isnull", False),
                        models.Q(("evidence_ref", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="hover_evidence_link_exactly_one_kind",
            ),
        ),
    ]
