#!/usr/bin/env bash
set -e

export DJANGO_SETTINGS_MODULE=zproject.test_settings

if [[ ${HOVER_DEV_CONTAINER:-} == 1 ]]; then
    test_database="hover_test_${HOVER_DEV_INSTANCE_ID}"
    test_template="${test_database}_template"
    postgres_host="${HOVER_DEV_DATABASE_HOST}"
    postgres_user="${HOVER_DEV_DATABASE_USER}"
    export PGPASSWORD="${HOVER_DEV_DATABASE_PASSWORD}"
else
    test_database=zulip_test
    test_template=zulip_test_template
    test_base=zulip_test_base
    postgres_host=localhost
    postgres_user=zulip
fi

for database_name in "$test_database" "$test_template" "${test_base:-}"; do
    [[ -z $database_name || $database_name =~ ^[a-z0-9_]+$ ]] || exit 1
done

create_zulip_test() {
    if [[ -n ${test_base:-} ]]; then
        psql -v ON_ERROR_STOP=1 -h "$postgres_host" -U "$postgres_user" postgres \
            -v test_database="$test_database" -v test_base="$test_base" <<'EOF'
DROP DATABASE IF EXISTS :"test_database";
CREATE DATABASE :"test_database" TEMPLATE :"test_base";
EOF
    else
        psql -v ON_ERROR_STOP=1 -h "$postgres_host" -U "$postgres_user" postgres \
            -v test_database="$test_database" <<'EOF'
DROP DATABASE IF EXISTS :"test_database";
CREATE DATABASE :"test_database";
EOF
        psql -v ON_ERROR_STOP=1 -h "$postgres_host" -U "$postgres_user" \
            "$test_database" -c "CREATE EXTENSION IF NOT EXISTS pgroonga;"
    fi
}

create_zulip_test_template() {
    psql -v ON_ERROR_STOP=1 -h "$postgres_host" -U "$postgres_user" postgres \
        -v test_database="$test_database" -v test_template="$test_template" <<'EOF'
DROP DATABASE IF EXISTS :"test_template";
CREATE DATABASE :"test_template" TEMPLATE :"test_database";
EOF
}

mkdir -p zerver/tests/fixtures

PGHOST="$postgres_host" PGUSER="$postgres_user" \
    "$(dirname "$0")/../scripts/setup/terminate-psql-sessions" \
    "$test_database" "$test_template" ${test_base:+"$test_base"}

create_zulip_test

if [[ ${HOVER_DEV_CONTAINER:-} != 1 ]]; then
    "$(dirname "$0")/../scripts/setup/flush-memcached"
fi

./manage.py migrate --noinput
./manage.py get_migration_status --output="migration_status_test"

# This next line can be simplified to "-n0" once we fix our app (and tests) with 0 messages.
./manage.py populate_db --test-suite -n30 --threads=1 \
    --max-topics=3 \
    --direct-message-groups=0 --personals=0 --percent-direct-message-groups=0 --percent-personals=0 \
    --percent-attachments=0

./manage.py dumpdata \
    zerver.UserProfile zerver.Stream zerver.Recipient \
    zerver.Subscription zerver.Message zerver.DirectMessageGroup zerver.Realm \
    zerver.UserMessage zerver.Client \
    zerver.DefaultStream >zerver/tests/fixtures/messages.json

# create pristine template database, for fast fixture restoration after tests are run.
create_zulip_test_template
